### ISSUE TITLE
Update keyboard shortcuts quick reference

### ISSUE THREAD

**Issue by rockivist** [marktriggs/in_a_rush#1]
I was surprised that ASpace already has some stock keyboard shortcuts - hitting ? in the staff app brings up a list. Would be good if the plugin added to that list.

FWIW, here's what the stock shortcuts are:

`

Action | Shortcut
-- | --
This shortcut reference | Shift ?
Close a modal window (e.g., this one) | ESC
Save the record being edited | Ctrl s
Close a record being edited | Ctrl x
Open Browse menu | Shift b
Open Create menu | Shift c
`

**Comment by marktriggs** [comment]
Hah, I hadn't seen those either.  I've merged them in...

**Comment by rockivist** [comment]
What, no ↑↑↓↓←→←→BA?

**Comment by marktriggs** [comment]
Hah, I did seriously think about it :)
