### ISSUE TITLE
As a staff user, I'd like to be able to create top-level records with a keyboard shortcut

### ISSUE THREAD

**Issue by rockivist** [marktriggs/in_a_rush#2]
One class of keyboard shortcuts could be for the creation of top-level record types: resources, accessions, digital objects, subjects, and agents. My suggestions:

Action | Shortcut
-- | --
Create resource | cr
Create accession | ca
Create digital object | cd
Create subject | cs
Create person | cp
Create corporate body | cb
Create family | cf

**Comment by marktriggs** [comment]
Check the master branch!

**Comment by rockivist** [comment]
Works like a charm. Especially love how you made the keystrokes appear in the upper left.
