### ISSUE TITLE
As a staff user, I'd like to be able to add subrecords with a keyboard shortcut

### ISSUE THREAD

**Issue by rockivist** [marktriggs/in_a_rush#3]
Another class of keyboard shortcut could be for adding subrecords to an existing top-level record type. 

Action | Shortcut
-- | --
Add dates subrecord | ad
Add extent subrecord | ae
Add agent link | al
Add subject link | as
Add external document | ax
Add container instance | ac
Add digital object instance | ao
Add note | an
Add event | av
Add assessment | aa

These are not all relevant for all record types. Shortcut should only work if the current record allowed for that subrecord type. Should only work in edit mode.

There are more subrecord types that could be included, but obvious letter choices would start to overlap, so maybe not every subrecord type needs a shortcut.

**Comment by marktriggs** [comment]
Thinking about this one... an issue with the edit forms is that you're often focused on an input element, so regular keystrokes won't get picked up as shortcuts.  It seems like it would be nice for these shortcuts to work even if you happened to have a text box focused, for example.

What if we prefixed the edit commands with something like `Ctrl-e`?  So `Ctrl-e d` for a date subrecord, `Ctrl-e e` for an extent, etc..  `Ctrl-a` might be more mnemonic but conflicts with "Select all", which I can see annoying people (people like me).  What do you think?

**Comment by rockivist** [comment]
Good thinking. Ctrl-e is an elegant way around the input focus issue. I’m all for it.

**Comment by marktriggs** [comment]
Cool.  There's a first cut at these there now too.  I added a few bonuses:

  * If the shortcut is `Control-e d`, you can get away with hitting `Control-e Control-d`.  Seemed nice to be a little forgiving (for once)

  * `Control-e f` focuses the first field in the form.  Handy for new records...

  * `Control-e k` offers to remove the currently focused subrecord.  Handy when you accidentally add the wrong subrecord...

**Comment by rockivist** [comment]
Looks good!

A few observations:

- When adding a container instance using `Ctrl-e c`, the form doesn't focus on the newly added container subrecord
- `Ctrl-e k` doesn't seem to be working, at least in Accession and Resource records. Nothing happens and the "k" is input as text.
- `Ctrl-k` isn't working in Resource records. Now it calls up the Merge drop-down. Not sure if this is the plugin
- On that topic, did you change it from `Ctrl-x`? That's what the current default keystroke is for closing a record.
- `Ctrl-e n` isn't working in Resource records. Keystrokes display in the upper left, but the new note subrecord isn't added.

**Comment by marktriggs** [comment]
Ah yes... running an outdated version of ArchivesSpace seems to have been my undoing.  I just updated and I'm seeing all that too.

Working on it! :construction:

**Comment by marktriggs** [comment]
Right!  I believe I've addressed those issues now.

And yeah, I forgot to mention Ctrl-x: I did change it because I thought it risked overriding the Cut function.  Thoughts on that?  There's no technical motivation either way, so just a question of what's more or less surprising to Real People I guess :)

**Comment by rockivist** [comment]
"Ctrl-e K" behaves inconsistently in Agent Links. Works fine if the focus is in Role or Agent boxes, but fails when in the Relator box. The K still inputs as text.

**Comment by rockivist** [comment]
"Ctrl-e k" doesn't work in Resource notes

**Comment by rockivist** [comment]
Thinking about Ctrl-k vs. Ctrl-x. I follow your logic about the change, but I worry that there may be confusion between "Ctrl-e k" and "Ctrl-k". 

What would you think about changing Remove current subrecord from "Ctrl-e k" to "Ctrl-e r"? That would avoid the confusion, and the r might be easier to remember as standing for "remove".

Everything looks good otherwise.

**Comment by marktriggs** [comment]
Thanks Mike!

Annoyingly, there's not much I can do about the inconsistency when the agent Relator field is focused.  The combo box widget used for that typeahead is grabbing the keystrokes before my code even has its pants on, so I never get the chance to act on them.  We might have to live with that I'm afraid.

The notes case was fixable, though, and that should be working now.

Switching to "Ctrl-e r" seems good to me, yeah.  I've updated that too.

**Comment by rockivist** [comment]
All looking very good. One last comment:

Behavior of `Ctrl-k` is inconsistent. In agents, subjects, DOs, resources, and accessions, in view mode it does nothing (more accurately if follows default Chrome behavior, which is to start a web search in the address bar). Behavior in edit mode is all over the place. For agents and subjects, from edit mode Ctrl-k will move you into view mode for that record. For resources and digital objects, it will refresh the page from the last save, staying in edit mode. For access records, it moves you back to the accession browse screen.

Would it be possible for Ctrl-k to always move you from Edit mode to View mode, and from View mode to browse mode for that record type?

**Comment by marktriggs** [comment]
Hmm yeah.  It's inconsistent because it just clicks the "Cancel" button, and the cancel button is inconsistent :)

I've just pushed a patch to modify ctrl-k to work backward through the breadcrumb list, which I think gives the behavior you're describing.  One small difference is if you're in browse mode and hit Ctrl-k you'll end up at the home screen, but that seems consistent in its way...

**Comment by rockivist** [comment]
This looks great! I think the plugin is ready for the big time.
