### ISSUE TITLE
As a staff user, I'd like to be able to navigate ASpace with additional keyboard shortcuts

### ISSUE THREAD

**Issue by rockivist** [marktriggs/in_a_rush#4]
Here's the navigation keyboard shortcuts at the moment:

Core code:

Action | Shortcut
-- | --
This shortcut reference | Shift ?
Close a modal window (e.g., this one) | ESC
Save the record being edited | Ctrl s
Close a record being edited | Ctrl x
Open Browse menu | Shift b
Open Create menu | Shift c

In first release of plugin:

Action | Shortcut
-- | --
Go to search | /
Go to next record in search results | j
Go to previous record in search results | k

Possible additions:

Action | Shortcut
-- | --
Go to home screen | gh
Go to browse accessions | ga
Go to browse resources | gr
Go to browse digital objects | go
Go to browse subjects | gs
Go to browse agents | ga
Go to Manage Top Containers | gt

**Comment by marktriggs** [comment]
Check the master branch!

**Comment by rockivist** [comment]
It's marvelous.
