### ISSUE TITLE
Fix navigation shortcuts in help menu

### ISSUE THREAD

**Issue by rockivist** [marktriggs/in_a_rush#5]
In the "?" keyboard shortcut pop-up, the shortcuts for "Open 'Browse' menu" and "Open 'Create' menu" are listed as B and C respectively. While I that is technically correct - both Shift-b and B (with caps lock on) work, it would probably be clearer to leave them as the default Shift-b and Shift-c. 

I think having shift precede opening menus is a good mnemonic, and distinguishes opening menus from the other navigation options, which move your focus on the screen rather than opening up something that isn't visible.

With that in mind, would it make sense to make "Shift - \" (or | I guess) open up Advanced search?

**Comment by marktriggs** [comment]
Yeah, that makes sense to me.  I've modified it to show "Shift-c"/'Shift-b" for those shortcuts.  I think this might stop the capslock version from working (can't immediately test because I disable capslock :P), but that doesn't seem like a great loss to me.

I added "Shift-|" to show/hide the advanced search too.  I went with pipe because "Shift--" looked a little confusing :)

**Comment by rockivist** [comment]
Looks good. You are right - capslock no longer works. But Shift-c/shift-b both with with capslock on, which I think is more consistent.

I meant `Shift-\`, not `Shift- -` (the escaping tripped me up). The latter would definitely have been confusing. Shift-\ and Shift-| are the same keystroke, really, but for consistency with \ being the regular search nav key, could we call the advanced search keystroke `Shift-\` ?

**Comment by marktriggs** [comment]
Yep, sure.  Just added!

**Comment by rockivist** [comment]
Sorry I went radio silent on this for so long - life got busy. This looks good. 

Somewhat related - when you have a moment, will you update the README?

**Comment by marktriggs** [comment]
No worries...

... there's a README?  Holy crap!  So there is.  Yes, I'll update that :)

**Comment by marktriggs** [comment]
README updated!  Let me know if there's anything you think the public needs to know that I've missed :)

**Comment by rockivist** [comment]
Looks good to me! Thanks for collaborating on this - always a pleasure!

**Comment by marktriggs** [comment]
Likewise :)
